apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: gmao
  labels:
    app: ai-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    app: ai-service
