{{- if and .Values.backend.enabled .Values.backend.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.backend.persistence.claimName }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
{{- range .Values.backend.persistence.accessModes }}
    - {{ . | quote }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.backend.persistence.size }}
{{- end }}
