{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name }}
    spec:
      containers:
        - name: {{ .Values.frontend.name }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
              name: http
          resources:
            requests:
              cpu: {{ .Values.frontend.resources.requests.cpu | quote }}
              memory: {{ .Values.frontend.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.frontend.resources.limits.cpu | quote }}
              memory: {{ .Values.frontend.resources.limits.memory | quote }}
          startupProbe:
            httpGet:
              path: {{ .Values.frontend.probes.path }}
              port: {{ .Values.frontend.containerPort }}
            periodSeconds: {{ .Values.frontend.probes.startup.periodSeconds }}
            timeoutSeconds: {{ .Values.frontend.probes.startup.timeoutSeconds }}
            failureThreshold: {{ .Values.frontend.probes.startup.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.frontend.probes.path }}
              port: {{ .Values.frontend.containerPort }}
            periodSeconds: {{ .Values.frontend.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.frontend.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.frontend.probes.readiness.failureThreshold }}
          livenessProbe:
            httpGet:
              path: {{ .Values.frontend.probes.path }}
              port: {{ .Values.frontend.containerPort }}
            periodSeconds: {{ .Values.frontend.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.frontend.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.frontend.probes.liveness.failureThreshold }}
{{- end }}

