{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.mysql.service.type }}
  selector:
    app: {{ .Values.mysql.name }}
  ports:
    - name: mysql
      port: {{ .Values.mysql.service.port }}
      targetPort: {{ .Values.mysql.service.targetPort }}
{{- end }}

