{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: gmao-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: {{ .Values.secrets.springDatasourceUsername | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secrets.springDatasourcePassword | quote }}
  APP_JWT_SECRET: {{ .Values.secrets.appJwtSecret | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.secrets.mysqlRootPassword | quote }}
  MYSQL_DATABASE: {{ .Values.secrets.mysqlDatabase | quote }}
  MYSQL_USER: {{ .Values.secrets.mysqlUser | quote }}
  MYSQL_PASSWORD: {{ .Values.secrets.mysqlPassword | quote }}
  GF_SECURITY_ADMIN_USER: {{ .Values.secrets.grafanaAdminUser | default "admin" | quote }}
  GF_SECURITY_ADMIN_PASSWORD: {{ .Values.secrets.grafanaAdminPassword | default "<CHANGE_ME_GRAFANA_PASSWORD>" | quote }}
{{- end }}
