apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - config/configmap.yaml
  - secrets/secrets.example.yaml
  - mysql/service.yaml
  - mysql/statefulset.yaml
  - ai-service/pvc.yaml
  - ai-service/service.yaml
  - ai-service/deployment.yaml
  - backend/uploads-pvc.yaml
  - backend/service.yaml
  - backend/deployment.yaml
  - frontend/service.yaml
  - frontend/deployment.yaml
  - ollama/pvc.yaml
  - ollama/service.yaml
  - ollama/deployment.yaml
  - ingress/ingress.yaml
  - autoscaling/hpa.yaml
  - monitoring/prometheus.yaml
  - monitoring/grafana.yaml
